version: '3'
services:
  app:
    container_name: mws_app
    #restart: always
    ports:
      - "5001:5001"
      - "4000:4000"
      - "3001:3000"
    build:
      context: ./containers/backend
    volumes:
      - './app:/app'

  nginx:
    container_name: mws_nginx
    #      restart: always
    image: nginx:latest
    ports:
      - "8080:80"
      - "80:80"
      - "8081:8081"
    volumes:
      - './app:/var/www/'
      - './containers/nginx/conf.d:/etc/nginx/conf.d'

  postgis:
    container_name: mws_postgis
    #      restart: always
    image: postgis/postgis:14-3.3
    ports:
      - "5432:5432"
    volumes:
      - mws_postgresvolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mws
      - POSTGRES_USER=mws_user
      - POSTGRES_PASSWORD=3b2797efdd871707af524ba41b78bd22

  redis:
    container_name: mws_redis
    #      restart: always
    image: redis:6-buster
    ports:
      - "6379:6379"
    volumes:
      - mws_redissvolume:/data
    command: redis-server --requirepass k6B6daVKj8n~am

  swagger:
    container_name: mws_swagger
    #      restart: always
    image: swaggerapi/swagger-ui:latest
    #ports:
    #  - "8081:8080"
    environment:
      - API_URL=http://localhost:8080/api/v1/swagger/  #http://localhost:80/api/swagger

volumes:
  mws_postgresvolume:
  mws_redissvolume:

